# Modify name if deploying multiple instances
name = "subbox"

main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# [placement]
# mode = "smart"

# Environment variables
# Modify these to use the correct environment variables
[vars]
ADMIN_USERNAME = "jiyue"
ADMIN_PASSWORD = "jiyue-99-KK" # Change this to a secure password
JWT_SECRET = "qAUtMswdEqiVa8LBKgt1tpybFU0mB84r" # Change this to a secure secret key
SESSION_TAG = "0"
SESSION_DURATION = "7d"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "sub-box-db" # Change this to the name of your D1 database
database_id = "139770b2-b1e0-4a1a-8e42-00b178897357" # wrangler d1 info <YOUR_DATABASE_NAME>

[observability.logs]
enabled = true

# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "prod-sub-box-next-inc-cache"
